name = "webauthn"
main = "src/index.ts"
compatibility_date = "2023-02-27"

kv_namespaces = [
    { binding = "Storage", id = "4f43b285fbd746ee82b578d0c31013b4", preview_id = "4f43b285fbd746ee82b578d0c31013b4" }
]
